#!/usr/bin/env bash

GO_VERSION=go1.15.6
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "=> Use ${GO_VERSION}"
    gvm use $GO_VERSION
fi

# golang migrate
MIGRATE_PATH=$(which migrate)
if [[ "$MIGRATE_PATH" != *"$GO_VERSION"* ]]; then
    echo "=> Installing migrate"
    go get -u -d github.com/golang-migrate/migrate/cmd/migrate github.com/lib/pq github.com/hashicorp/go-multierror
    go build -tags 'postgres' -o $GOPATH/bin/migrate github.com/golang-migrate/migrate/cmd/migrate
fi

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    source ${BASH_SOURCE%/*}/environment ./service/$SERVICE_NAME || exit $?

    URL="postgres://$APP_SERVER_DB_USER:$APP_SERVER_DB_PASSWORD@$APP_SERVER_DB_HOST:$APP_SERVER_DB_PORT/$APP_SERVER_DB_NAME?sslmode=disable"

    echo "=> Migrate URL $URL"

    migrate \
    -path ./database/migrations \
    -database $URL down $1

done

