#!/usr/bin/env bash

# copy development env
cp .env.development .env

# stop
source ${BASH_SOURCE%/*}/stop $1 || exit $?

# start database
source ${BASH_SOURCE%/*}/start-database $1 || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# start nginx
source ${BASH_SOURCE%/*}/start-nginx $1 || exit $?

# start services
source ${BASH_SOURCE%/*}/start-services $1 || exit $?

