#!/usr/bin/env bash

# stop nginx
source ${BASH_SOURCE%/*}/stop-nginx || exit $?

# start nginx
if [ $(uname) = "Linux" ]; then
    echo
    echo "=> Starting nginx (Linux)"
    echo
    docker run --name hrm-nginx -v "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro" -p 8082:80 -d nginx nginx-debug
else
    echo
    echo "=> Starting nginx (MacOS)"
    echo
    docker run --name hrm-nginx -v "${PWD}/nginx.conf:/etc/nginx/nginx.macos.conf:ro" -p 8082:80 -d nginx nginx-debug
fi
