#!/usr/bin/env bash

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

# retry
source ${BASH_SOURCE%/*}/retry || exit $?

# stop database
source ${BASH_SOURCE%/*}/stop-database $APP_SERVER_DB_SERVICE || exit $?

# start database
echo "=> Start database"

if [ $APP_SERVER_DB_SERVICE = "docker" ]; then

    echo "=> Start database - docker service"

    docker run --hostname postgres --name hrm-shared \
    -e POSTGRES_USER=$APP_SERVER_DB_USER \
    -e POSTGRES_PASSWORD=$APP_SERVER_DB_PASSWORD \
    -e POSTGRES_DB=$APP_SERVER_DB_NAME \
    -p ${APP_SERVER_DB_PORT}:5432 -d \
    postgres:10.4-alpine || exit $?

elif [ $APP_SERVER_DB_SERVICE = "local" ]; then

    echo "=> Start database - local service"

    sudo service postgresql start
    sudo -u postgres createuser $APP_SERVER_DB_USER
    sudo -u postgres createdb $APP_SERVER_DB_NAME
    sudo -u postgres \
        psql -c "grant all privileges on database $APP_SERVER_DB_NAME to $APP_SERVER_DB_USER;"
    sudo -u postgres \
        psql -c "alter user $APP_SERVER_DB_USER with password '$APP_SERVER_DB_PASSWORD';"

fi

# pgcrypto for uuids
export PGPASSWORD=$APP_SERVER_DB_PASSWORD
retry_cmd psql --host=$APP_SERVER_DB_HOST \
     --port=$APP_SERVER_DB_PORT \
	 --username=$APP_SERVER_DB_USER \
     --command="CREATE EXTENSION pgcrypto;" \
     $APP_SERVER_DB_NAME

echo "=> Start database - running on ${APP_SERVER_DB_HOST}:${APP_SERVER_DB_PORT}"

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

# main database
APP_MAIN_DB_NAME=$APP_SERVER_DB_NAME

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    # service specific .env
    if [ $APP_SERVER_DB_SERVICE = "docker" ] || [ $APP_SERVER_DB_SERVICE = "local" ]; then
        if [ -f "./service/$SERVICE_NAME/.env.development" ]; then
            cp "./service/$SERVICE_NAME/.env.development" "./service/$SERVICE_NAME/.env"
        fi
    fi

    # service specific .env
    if [ $APP_SERVER_DB_SERVICE = "ci" ]; then
        if [ -f "./service/$SERVICE_NAME/.env.ci" ]; then
            cp "./service/$SERVICE_NAME/.env.ci" "./service/$SERVICE_NAME/.env"
        fi
    fi

    if [ -f "./service/$SERVICE_NAME/.env" ]; then

        # reset APP_SERVER_DB_NAME as each service should define
        # a unique database name in their local env
        export APP_SERVER_DB_NAME=""

        # load service specific environment
        source ${BASH_SOURCE%/*}/environment ./service/$SERVICE_NAME || exit $?

        echo "=> Start database - creating database name $APP_SERVER_DB_NAME owner $APP_SERVER_DB_USER"

        export PGPASSWORD=$APP_SERVER_DB_PASSWORD
        retry_cmd psql --host=$APP_SERVER_DB_HOST \
            --port=$APP_SERVER_DB_PORT \
            --username=$APP_SERVER_DB_USER \
            --command="CREATE DATABASE \"${APP_SERVER_DB_NAME}\" OWNER \"${APP_SERVER_DB_USER}\";" \
            $APP_MAIN_DB_NAME

        # pgcrypto for uuids
        retry_cmd psql --host=$APP_SERVER_DB_HOST \
            --port=$APP_SERVER_DB_PORT \
            --username=$APP_SERVER_DB_USER \
            --command="CREATE EXTENSION pgcrypto;" \
            $APP_SERVER_DB_NAME
    fi
done
