#!/usr/bin/env bash

echo
echo "=> Starting services"
echo

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    if [ -f "./service/$SERVICE_NAME/.env" ]; then

        # reset APP_SERVER_PORT as each service should define
        # a unique server port in their local env
        export APP_SERVER_PORT=""

        # build and run service
        cd service/$SERVICE_NAME

        # NOTE: we shift into the service directory before sourcing
        # the environment so $PWD is correct for APP_SERVER_HOME

        # copy development env
        cp .env.development .env

        # add local env (runtime secrets we don't actually want committed to git)
        cat .env.local >> .env

        # load service specific environment
        source ../../${BASH_SOURCE%/*}/environment || exit $?

        # build server
        SERVER_NAME="hrm-${SERVICE_NAME}-server"
        rm -f $SERVER_NAME
        go build -o $SERVER_NAME ./cmd/server

        echo "Running server $SERVER_NAME"
        ./$SERVER_NAME&
        cd -
    fi
done