#!/usr/bin/env bash

NGINX_RUNNING=$(docker ps -a | grep "hrm-krakend")
if [[ ! -z "${NGINX_RUNNING}" ]]; then
    echo
    echo "=> Stopping krakend"
    echo
    docker stop hrm-krakend
    docker rm hrm-krakend
fi
