#!/usr/bin/env bash

# copy development env
cp .env.development .env

# stop
source ${BASH_SOURCE%/*}/stop-services || exit $?

# stop nginx
source ${BASH_SOURCE%/*}/stop-nginx

# stop database
source ${BASH_SOURCE%/*}/stop-database || exit $?

