#!/usr/bin/env bash

echo
echo "=> Test common"
echo

# "docker" or "local"
export APP_SERVER_DB_SERVICE=docker
if [ -n "$1" ]; then
    export APP_SERVER_DB_SERVICE=$1
    shift
fi

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

dir="common"
for f in "$dir"/*; do
    echo "=> Test common - $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./... || exit $?
    fi
    cd -
done

dir="common/type"
for f in "$dir"/*; do
    echo "=> Test common - $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./... || exit $?
    fi
    cd -
done
