#!/usr/bin/env bash

GO_VERSION=go1.13.3
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "Using ${GO_VERSION}"
    gvm use $GO_VERSION
fi

# copy development env
cp .env.development .env

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

if ! [[ -n ${APP_DB_SERVICE} ]]; then
    echo "=> (test-ci) Missing APP_DB_SERVICE"
    exit 1
fi

# start database
source ${BASH_SOURCE%/*}/start-database || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# test client
source ${BASH_SOURCE%/*}/test-client || exit $?

# test common
source ${BASH_SOURCE%/*}/test-common || exit $?

# test service
source ${BASH_SOURCE%/*}/test-service || exit $?

# stop services
source ${BASH_SOURCE%/*}/stop-database || exit $?
