stages:
  - test

test:
  stage: test
  image: golang:1.13.5-alpine3.11
  before_script:
    - apk update
    - apk add openrc --no-cache
    - apk add docker --no-cache
    - service docker status
    - apk add postgresql-client --no-cache
  script:
    - ./script/test
