stages:
  - test
  - build
  - deploy

test-app:
  stage: test
  image: cirrusci/flutter:stable
  before_script:
    - cd app
    - flutter channel beta
    - flutter upgrade
    - flutter pub get
    - flutter clean
    - cd -
  script:
    - cd app
    - flutter test test/*
    - cd -

test-server:
  stage: test
  image: golang:1.15.2-alpine3.12
  variables:
    POSTGRES_DB: hrm
    POSTGRES_USER: hrm-user
    POSTGRES_PASSWORD: hrm-pass
  services:
    - postgres:10.4-alpine
  before_script:
    - apk add bash --no-cache
    - apk add libc-dev --no-cache
    - apk add gcc --no-cache
    - apk add git --no-cache
    - apk add postgresql-client --no-cache
  script:
    - cd server
    - ./script/test-ci
    - cd -

# build-all:
#   stage: build
#   image: google/cloud-sdk
#   services:
#     - docker:18.09.7-dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#   script:
#     - ./script/build
#   only:
#     refs:
#       - master

# deploy-all:
#   stage: deploy
#   image: google/cloud-sdk
#   script:
#     - ./script/deploy
#   only:
#     refs:
#       - master
