stages:
  - test
  - build
  - deploy

test-all:
  stage: test
  image: golang:1.13.5-alpine3.11
  variables:
    POSTGRES_DB: holyragingmages-shared
    POSTGRES_USER: holyragingmages-user
    POSTGRES_PASSWORD: holyragingmages-pass
  services:
    - postgres:10.4-alpine
  before_script:
    - apk add bash --no-cache
    - apk add libc-dev --no-cache
    - apk add gcc --no-cache
    - apk add git --no-cache
    - apk add postgresql-client --no-cache
  script:
    - ./script/test-ci

build-all:
  stage: build
  image: google/cloud-sdk
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - ./script/build
  only:
    refs:
      - master

deploy-all:
  stage: deploy
  image: google/cloud-sdk
  script:
    - ./script/deploy
  only:
    refs:
      - master
