name: holyragingmages
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <2.12.0"

dependencies:
  flutter:
    sdk: flutter

  # Get current device information from within the Flutter application.
  device_info_plus: ^0.6.0

  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.3.2

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, 
  # FormData, Request Cancellation, File downloading, Timeout etc.
  dio: ^3.0.10

  # Provides APIs for debugging and error logging. This library introduces abstractions 
  # similar to those used in other languages, such as the Closure JS Logger and java.util.logging.Logger.
  logging: ^0.11.4

  # Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS and 
  # macOS, SharedPreferences on Android, etc.). Data may be persisted to disk asynchronously, and there 
  # is no guarantee that writes will be persisted to disk after returning, so this plugin must not be 
  # used for storing critical data.
  shared_preferences: ^0.5.12+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Google Sign In https://developers.google.com/identity/
  google_sign_in: 4.5.6

  # Common words
  english_words: ^3.1.5

  # A carousel slider widget.
  # https://pub.dev/packages/carousel_slider
  # https://github.com/serenader2014/flutter_carousel_slider
  carousel_slider: ^2.3.1

  # A minimalistic Flutter game engine.
  flame: ^0.28.0 

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/signin/google_logo.png
    # Mage - Red Stripe Necromancer
    - assets/images/mages/red-stripe-necromancer/idle/idle_000.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_001.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_002.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_003.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_004.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_005.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_006.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_007.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_008.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_009.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_010.png
    - assets/images/mages/red-stripe-necromancer/idle/idle_011.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_000.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_001.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_002.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_003.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_004.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_005.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_006.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_007.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_008.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_009.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_010.png
    - assets/images/mages/red-stripe-necromancer/casting/casting_011.png
    # Mage - Red Stripe Druid
    - assets/images/mages/red-stripe-druid/idle/idle_000.png
    - assets/images/mages/red-stripe-druid/idle/idle_001.png
    - assets/images/mages/red-stripe-druid/idle/idle_002.png
    - assets/images/mages/red-stripe-druid/idle/idle_003.png
    - assets/images/mages/red-stripe-druid/idle/idle_004.png
    - assets/images/mages/red-stripe-druid/idle/idle_005.png
    - assets/images/mages/red-stripe-druid/idle/idle_006.png
    - assets/images/mages/red-stripe-druid/idle/idle_007.png
    - assets/images/mages/red-stripe-druid/idle/idle_008.png
    - assets/images/mages/red-stripe-druid/idle/idle_009.png
    - assets/images/mages/red-stripe-druid/idle/idle_010.png
    - assets/images/mages/red-stripe-druid/idle/idle_011.png
    - assets/images/mages/red-stripe-druid/casting/casting_000.png
    - assets/images/mages/red-stripe-druid/casting/casting_001.png
    - assets/images/mages/red-stripe-druid/casting/casting_002.png
    - assets/images/mages/red-stripe-druid/casting/casting_003.png
    - assets/images/mages/red-stripe-druid/casting/casting_004.png
    - assets/images/mages/red-stripe-druid/casting/casting_005.png
    - assets/images/mages/red-stripe-druid/casting/casting_006.png
    - assets/images/mages/red-stripe-druid/casting/casting_007.png
    - assets/images/mages/red-stripe-druid/casting/casting_008.png
    - assets/images/mages/red-stripe-druid/casting/casting_009.png
    - assets/images/mages/red-stripe-druid/casting/casting_010.png
    - assets/images/mages/red-stripe-druid/casting/casting_011.png
    # Mage - Red Fairy
    - assets/images/mages/red-fairy/idle/idle_000.png
    - assets/images/mages/red-fairy/idle/idle_001.png
    - assets/images/mages/red-fairy/idle/idle_002.png
    - assets/images/mages/red-fairy/idle/idle_003.png
    - assets/images/mages/red-fairy/idle/idle_004.png
    - assets/images/mages/red-fairy/idle/idle_005.png
    - assets/images/mages/red-fairy/idle/idle_006.png
    - assets/images/mages/red-fairy/idle/idle_007.png
    - assets/images/mages/red-fairy/idle/idle_008.png
    - assets/images/mages/red-fairy/idle/idle_009.png
    - assets/images/mages/red-fairy/idle/idle_010.png
    - assets/images/mages/red-fairy/idle/idle_011.png
    - assets/images/mages/red-fairy/casting/casting_000.png
    - assets/images/mages/red-fairy/casting/casting_001.png
    - assets/images/mages/red-fairy/casting/casting_002.png
    - assets/images/mages/red-fairy/casting/casting_003.png
    - assets/images/mages/red-fairy/casting/casting_004.png
    - assets/images/mages/red-fairy/casting/casting_005.png
    - assets/images/mages/red-fairy/casting/casting_006.png
    - assets/images/mages/red-fairy/casting/casting_007.png
    - assets/images/mages/red-fairy/casting/casting_008.png
    - assets/images/mages/red-fairy/casting/casting_009.png
    - assets/images/mages/red-fairy/casting/casting_010.png
    - assets/images/mages/red-fairy/casting/casting_011.png
    # Mage - Dark Armoured
    - assets/images/mages/dark-armoured/idle/idle_000.png
    - assets/images/mages/dark-armoured/idle/idle_001.png
    - assets/images/mages/dark-armoured/idle/idle_002.png
    - assets/images/mages/dark-armoured/idle/idle_003.png
    - assets/images/mages/dark-armoured/idle/idle_004.png
    - assets/images/mages/dark-armoured/idle/idle_005.png
    - assets/images/mages/dark-armoured/idle/idle_006.png
    - assets/images/mages/dark-armoured/idle/idle_007.png
    - assets/images/mages/dark-armoured/idle/idle_008.png
    - assets/images/mages/dark-armoured/idle/idle_009.png
    - assets/images/mages/dark-armoured/idle/idle_010.png
    - assets/images/mages/dark-armoured/idle/idle_011.png
    - assets/images/mages/dark-armoured/attacking/attacking_000.png
    - assets/images/mages/dark-armoured/attacking/attacking_001.png
    - assets/images/mages/dark-armoured/attacking/attacking_002.png
    - assets/images/mages/dark-armoured/attacking/attacking_003.png
    - assets/images/mages/dark-armoured/attacking/attacking_004.png
    - assets/images/mages/dark-armoured/attacking/attacking_005.png
    - assets/images/mages/dark-armoured/attacking/attacking_006.png
    - assets/images/mages/dark-armoured/attacking/attacking_007.png
    - assets/images/mages/dark-armoured/attacking/attacking_008.png
    - assets/images/mages/dark-armoured/attacking/attacking_009.png
    - assets/images/mages/dark-armoured/attacking/attacking_010.png
    - assets/images/mages/dark-armoured/attacking/attacking_011.png
    # Mage - Green Elven
    - assets/images/mages/green-elven/idle/idle_000.png
    - assets/images/mages/green-elven/idle/idle_001.png
    - assets/images/mages/green-elven/idle/idle_002.png
    - assets/images/mages/green-elven/idle/idle_003.png
    - assets/images/mages/green-elven/idle/idle_004.png
    - assets/images/mages/green-elven/idle/idle_005.png
    - assets/images/mages/green-elven/idle/idle_006.png
    - assets/images/mages/green-elven/idle/idle_007.png
    - assets/images/mages/green-elven/idle/idle_008.png
    - assets/images/mages/green-elven/idle/idle_009.png
    - assets/images/mages/green-elven/idle/idle_010.png
    - assets/images/mages/green-elven/idle/idle_011.png
    # Familliar - Brown Cyclops
    - assets/images/familliars/brown-cyclops-bat/idle/idle_000.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_001.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_002.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_003.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_004.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_005.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_006.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_007.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_008.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_009.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_010.png
    - assets/images/familliars/brown-cyclops-bat/idle/idle_011.png
    # Familliar - Brown Yeti
    - assets/images/familliars/brown-yeti/idle/idle_000.png
    - assets/images/familliars/brown-yeti/idle/idle_001.png
    - assets/images/familliars/brown-yeti/idle/idle_002.png
    - assets/images/familliars/brown-yeti/idle/idle_003.png
    - assets/images/familliars/brown-yeti/idle/idle_004.png
    - assets/images/familliars/brown-yeti/idle/idle_005.png
    - assets/images/familliars/brown-yeti/idle/idle_006.png
    - assets/images/familliars/brown-yeti/idle/idle_007.png
    - assets/images/familliars/brown-yeti/idle/idle_008.png
    - assets/images/familliars/brown-yeti/idle/idle_009.png
    - assets/images/familliars/brown-yeti/idle/idle_010.png
    - assets/images/familliars/brown-yeti/idle/idle_011.png
    # Familliar - Green Tribble
    - assets/images/familliars/green-tribble/idle/idle_000.png
    - assets/images/familliars/green-tribble/idle/idle_001.png
    - assets/images/familliars/green-tribble/idle/idle_002.png
    - assets/images/familliars/green-tribble/idle/idle_003.png
    - assets/images/familliars/green-tribble/idle/idle_004.png
    - assets/images/familliars/green-tribble/idle/idle_005.png
    - assets/images/familliars/green-tribble/idle/idle_006.png
    - assets/images/familliars/green-tribble/idle/idle_007.png
    - assets/images/familliars/green-tribble/idle/idle_008.png
    - assets/images/familliars/green-tribble/idle/idle_009.png
    - assets/images/familliars/green-tribble/idle/idle_010.png
    - assets/images/familliars/green-tribble/idle/idle_011.png
    # Familliar - Grey Cyclops
    - assets/images/familliars/grey-cyclops/idle/idle_000.png
    - assets/images/familliars/grey-cyclops/idle/idle_001.png
    - assets/images/familliars/grey-cyclops/idle/idle_002.png
    - assets/images/familliars/grey-cyclops/idle/idle_003.png
    - assets/images/familliars/grey-cyclops/idle/idle_004.png
    - assets/images/familliars/grey-cyclops/idle/idle_005.png
    - assets/images/familliars/grey-cyclops/idle/idle_006.png
    - assets/images/familliars/grey-cyclops/idle/idle_007.png
    - assets/images/familliars/grey-cyclops/idle/idle_008.png
    - assets/images/familliars/grey-cyclops/idle/idle_009.png
    - assets/images/familliars/grey-cyclops/idle/idle_010.png
    - assets/images/familliars/grey-cyclops/idle/idle_011.png
    # Familliar - Orange Spotted Tribble
    - assets/images/familliars/orange-spotted-tribble/idle/idle_000.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_001.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_002.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_003.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_004.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_005.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_006.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_007.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_008.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_009.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_010.png
    - assets/images/familliars/orange-spotted-tribble/idle/idle_011.png
    # Familliar - Purple Bat
    - assets/images/familliars/purple-bat/idle/idle_000.png
    - assets/images/familliars/purple-bat/idle/idle_001.png
    - assets/images/familliars/purple-bat/idle/idle_002.png
    - assets/images/familliars/purple-bat/idle/idle_003.png
    - assets/images/familliars/purple-bat/idle/idle_004.png
    - assets/images/familliars/purple-bat/idle/idle_005.png
    - assets/images/familliars/purple-bat/idle/idle_006.png
    - assets/images/familliars/purple-bat/idle/idle_007.png
    - assets/images/familliars/purple-bat/idle/idle_008.png
    - assets/images/familliars/purple-bat/idle/idle_009.png
    - assets/images/familliars/purple-bat/idle/idle_010.png
    - assets/images/familliars/purple-bat/idle/idle_011.png
    # Familliar - Purple Minotaur
    - assets/images/familliars/purple-minotaur/idle/idle_000.png
    - assets/images/familliars/purple-minotaur/idle/idle_001.png
    - assets/images/familliars/purple-minotaur/idle/idle_002.png
    - assets/images/familliars/purple-minotaur/idle/idle_003.png
    - assets/images/familliars/purple-minotaur/idle/idle_004.png
    - assets/images/familliars/purple-minotaur/idle/idle_005.png
    - assets/images/familliars/purple-minotaur/idle/idle_006.png
    - assets/images/familliars/purple-minotaur/idle/idle_007.png
    - assets/images/familliars/purple-minotaur/idle/idle_008.png
    - assets/images/familliars/purple-minotaur/idle/idle_009.png
    - assets/images/familliars/purple-minotaur/idle/idle_010.png
    - assets/images/familliars/purple-minotaur/idle/idle_011.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
