#!/usr/bin/env bash

echo
echo "=> Starting services"
echo

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    if [ -f "./service/$SERVICE_NAME/.env" ]; then

        # reset APP_PORT as each service should define
        # a unique server port in their local env
        export APP_PORT=""

        # build and run service
        cd service/$SERVICE_NAME

        # NOTE: we shift into the service directory before sourcing
        # the environment so $PWD is correct for APP_HOME

        # load service specific environment
        source ../../${BASH_SOURCE%/*}/environment || exit $?

        # build server
        SERVER_NAME="hrm-${SERVICE_NAME}-server"
        rm -f $SERVER_NAME
        go build -o $SERVER_NAME ./cmd/server

        echo "Running server $SERVER_NAME"
        ./$SERVER_NAME&
        cd -
    fi
done