#!/usr/bin/env bash

# service directory list
shopt -s dotglob
shopt -s nullglob
cd ./service
SERVICE_NAMES=(*)
cd -

for SERVICE_NAME in "${SERVICE_NAMES[@]}"; do

    if [ -f "./service/$SERVICE_NAME/.env" ]; then

        # stop server
        SERVER_NAME="hrm-${SERVICE_NAME}-server"

        PID=$(pgrep $SERVER_NAME)

        if [ -n "$PID" ]; then
            echo "Killing process $PID for $SERVER_NAME"
            kill $PID
            sleep 2
        fi
    fi
done

