#!/usr/bin/env bash

NGINX_RUNNING=$(docker ps | grep "hrm-nginx")
if [[ ! -z "${NGINX_RUNNING}" ]]; then
    echo
    echo "=> Stopping nginx"
    echo
    docker stop hrm-nginx
    docker rm hrm-nginx
fi
