#!/usr/bin/env bash

# stop database
echo "=> Stopping database";
if [ $APP_DB_SERVICE = "docker" ]; then
    echo "=> Stopping database docker service"

    docker ps -a | grep holyragingmages | awk '{print $1}' | xargs sh -c 'for arg do docker stop $arg; docker rm $arg; done' _

else
    echo "=> Stopping database local service"

     sudo -u postgres dropdb holyragingmages
     sudo -u postgres dropuser holyragingmages
     sudo service postgresql stop

fi

