#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/start-services || status=$?

if [ $status -ne 0 ]; then
    echo "Failed start-services" >&2
    exit $status
fi

source ${BASH_SOURCE%/*}/test || status=$?

if [ $status -ne 0 ]; then
    echo "Failed test" >&2
    exit $status
fi

source ${BASH_SOURCE%/*}/stop-services || status=$?

if [ $status -ne 0 ]; then
    echo "Failed stop-services" >&2
    exit $status
fi
