#!/usr/bin/env bash

# environment
cp .env.test .env
status=0
source ${BASH_SOURCE%/*}/environment || status=$?

if [ $status -ne 0 ]; then
    echo "Failed including environment" >&2
    exit $status
fi

# required for all environments
MODULES=( \
    'common/database' \
    'common/env' \
    'common/logger' \
    'common/model' \
    'common/repository' \
    'common/service' \
);

for MODULE in ${MODULES[@]}; do

    cd $MODULE
    go test -v -count 1 . || exit $?
    cd -

done
