#!/usr/bin/env bash

dir="common"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./ || exit $?
    fi
    cd -
done

dir="common/type"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./ || exit $?
    fi
    cd -
done

dir="service"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    export APP_HOME=$(pwd)
    echo "Testing => APP_HOME - ${APP_HOME}"
    if [ -f ".env.ci" ]; then
        echo "Testing => Sourcing service .env.ci"
        source .env.ci
    fi
    if [ -f "go.mod" ]; then
        go test -cover -count 1 ./... || exit $?
    fi
    cd -
done
