#!/usr/bin/env bash

dir="common"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -v -count 1 ./ || exit $?
    fi
    cd -
done

dir="common/type"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -v -count 1 ./ || exit $?
    fi
    cd -
done

dir="service"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    if [ -f "go.mod" ]; then
        go test -v -count 1 ./... || exit $?
    fi
    cd -
done
