#!/usr/bin/env bash

GO_VERSION=go1.13.3
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "Using ${GO_VERSION}"
    gvm use $GO_VERSION
fi

# start database
source ${BASH_SOURCE%/*}/start-database "docker" || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# test common
source ${BASH_SOURCE%/*}/test-common "docker" || exit $?

# test service
source ${BASH_SOURCE%/*}/test-service "docker" || exit $?

# stop services
source ${BASH_SOURCE%/*}/stop-database "docker" || exit $?
