#!/usr/bin/env bash

# copy ci env
cp .env.ci .env

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# test
source ${BASH_SOURCE%/*}/test-packages || exit $?
