#!/usr/bin/env bash

# required for all environments
MODULES=( \
    'common/database' \
    'common/env' \
    'common/logger' \
    'common/model' \
    'common/repository' \
    'common/service' \
);

for MODULE in ${MODULES[@]}; do

    cd $MODULE
    go test -v -count 1 . || exit $?
    cd -

done
