#!/usr/bin/env bash

dir="common"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    go test -v -count 1 ./... || exit $?
    cd -
done

dir="service"
for f in "$dir"/*; do
    echo "Testing => $f"
    cd $f
    go test -v -count 1 ./... || exit $?
    cd -
done
