#!/usr/bin/env bash

GO_VERSION=go1.13.3
if [ $(command -v gvm) ]; then
    source  ~/.gvm/scripts/gvm
    echo "Using ${GO_VERSION}"
    gvm use $GO_VERSION
fi

# copy locaL env
cp .env.local .env
status=0

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

# start services
source ${BASH_SOURCE%/*}/start-services || exit $?

# test
source ${BASH_SOURCE%/*}/test || exit $?

# stop services
source ${BASH_SOURCE%/*}/stop-services || exit $?
