#!/usr/bin/env bash

# copy ci env
cp .env.ci .env

# environment
source ${BASH_SOURCE%/*}/environment || exit $?

# start database
source ${BASH_SOURCE%/*}/start-database "ci" || exit $?

# migrate database
source ${BASH_SOURCE%/*}/db-migrate-up || exit $?

# test
source ${BASH_SOURCE%/*}/test-packages "ci" || exit $?
